### ISSUE TITLE
Login into admin panel showing error

### ISSUE THREAD

**Issue by LaravelDeveloperAjay** [sa1if3/online-admission-application-for-colleges#2]
ErrorException
Undefined variable: countCategory (View: D:\xampp\htdocs\onlineadmission\resources\views\vendor\multiauth\admin\home.blade.php)

**Comment by sa1if3** [comment]
There is some custom coded in vendor Folder which was missing. I have uploaded the entire folder.  Download the entire vendor folder and place it in the project folder.

Filename: /vendor/bitfumes/laravel-multiauth/src/Http/Controllers/AdminController.php

**Comment by LaravelDeveloperAjay** [comment]
i download complete but facing same error?
please help.

**Comment by sa1if3** [comment]
Works fine in my environment. Kindly fork/download a new copy and make sure
1. Imported online-admission.sql to your DB
2. Rename .env.backup to .env and set necessary config.
3. php artisan serve to run it
