### ISSUE TITLE
To disable OTP Verification simply navigate to your DB and Set default value of admins.where_am_i = 0

### ISSUE THREAD

**Issue by akowebs** [sa1if3/online-admission-application-for-colleges#4]
How do you change this? Maybe I don't understand properly

**Comment by sa1if3** [comment]
1. You need to open the database (preferably through PHPMyAdmin)
2.  Navigate to the table named `admins`
3. Alter and set `default value = 0` for the column `where_am_i`

**Comment by akowebs** [comment]
I imported the sql file and there is no table named where_am_i in admins.

**Comment by sa1if3** [comment]
Okay. Then do this. Instead of `admins` the table will be `students`

    1. You need to open the database (preferably through PHPMyAdmin)
    2. Navigate to the table named `students`
    3. Alter and set `default value = 0` for the column `where_am_i`

**Comment by akowebs** [comment]
That solves it. How do you disable the number check digit? So username can enter any number format.

**Comment by sa1if3** [comment]
Validation is done in the controllers and in some cases the blade files

Check `web.php` for necessary mapping.
